require('options.options')
require('custom.lazy')
require('telescope.telescope')
require('keymaps.keymaps')
require('treesitter.treesitter')
require('lsp.lsp')
require('lsp.mason')
require('options.cmp')
